### ISSUE TITLE
Space in xml.xsd URI

### ISSUE THREAD

**Issue by andreastai** [ebu/ebu-tt-d-xsd#1]
The URI for the schema location of the xml.xsd in ebutt_d.xsd has a leading space. Although the data type of the schema location attribute is xs:anyUri and spaces are allowed for that type, their use is discouraged and may also result in problems for schema validating processors.

**Comment by gazsp** [comment]
Fixed in https://github.com/ebu/ebu-tt-d-xsd/pull/3

**Comment by andreastai** [comment]
Fixed in commit 8e8e9417325ab94b4033985937487fde70e24158
