### ISSUE TITLE
Allow TTML attributes from TTML metadata namespace

### ISSUE THREAD

**Issue by andreastai** [ebu/ebu-tt-d-xsd#12]
The following change needs to be reflecred in the EBU-TT-D XSD for version 1.0.1

### Before
The TTML 1 metadata attributes ttm:agent and ttm:role were allowed on tt:body, tt:p and tt:span.
### After
TTML 1 metadata attributes can be used as defined in TTML 1.

**Comment by nigelmegitt** [comment]
This will now be resolved by the resolution to #22, i.e. #23.

**Comment by nigelmegitt** [comment]
Actually closed by #24.
