### ISSUE TITLE
ebuttm:documentIntendedTargetFormat constrained to maxOccurs=1

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-d-xsd#19]
The `maxOccurs` attribute is omitted from the definition of `ebuttm:documentIntendedTargetFormat`, and it defaults to 1, so if a document wants to signal intended conformance to multiple target formats, this is prohibited. Suggest adding `maxOccurs="unbounded"`.

**Comment by andreastai** [comment]
Thanks for spotting this.
