### ISSUE TITLE
Metadata handling should be factored out

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-d-xsd#22]
The way that EBU-TT metadata is handled at the moment has some issues:

1. It enforces the ordering requirement from EBU-TT Part 1 v1
2. It may need updating to match EBU-TT Metadata Tech3390.

I suggest we remove the metadata from the EBU-TT-D XSD and create a new XSD for EBU-TT Metadata specifically.

**Comment by andreastai** [comment]
Fine with me

**Comment by nigelmegitt** [comment]
I've been working on the metadata schema and we should be able to reference it from the EBU-TT-D schema.

**Comment by nigelmegitt** [comment]
I've got an updated metadata schema and will pull request it in to resolve this issue.

**Comment by nigelmegitt** [comment]
On integrating this I've realised there are dependencies on shared data types, which are not independently defined in the metadata schema, so there will be slightly more changes than just replacing `ebutt_metadata.xsd`.

**Comment by andreastai** [comment]
> I've been working on the metadata schema and we should be able to reference it from the EBU-TT-D schema.

We had and agreement to factor the metdata XSD out. This makes a lot of sense. It get referenced by other specifications (EBU-TT-D, Part 1 and Part 3). It can also be referenced by complete other specs.

We need to have a discussion first why this should be changed. Then we can think of changing codebase. As we haven't had this discussion, I unfortunately have to reject the corresponding PR.

**Comment by nigelmegitt** [comment]
The metadata XSD is now at ebu/ebu-tt-m-xsd and is designed so that it can be pulled in by using a git submodule. I will prepare a pull request here to make that work.

**Comment by nigelmegitt** [comment]
Closed by #24.
