### ISSUE TITLE
Metadata not allowed in style

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-d-xsd#9]
In TTML1, `<style>` cannot contain `<metadata>`, but the EBU-TT-D XSD allows it: https://github.com/ebu/ebu-tt-d-xsd/blob/d7dc05baaaec58bf1fa6bf0d96000933fe755ffa/ebutt_d.xsd#L86

**Comment by andreastai** [comment]
This was an error in the EBU-TT-D Version 1.0. It was fixed with version 1.0.1 and will be corrected.

**Comment by andreastai** [comment]
Resolved by #15
